dist: bionic
language: python

python:
  - "3.7"

install:
  - pip3 install -r requirements.txt

stages:
  - compile
  - pep8check
  - pylintcheck
  - test
  - test notebook
  - dockerbuild

jobs:
  include:
    - stage: compile
      script:
        - python3 -m compileall . assistance/*.py
    - stage: dockerbuild
      install: skip
      script:
        - docker build -f metadata/Dockerfile .
    - stage: pep8check
      install:
        - pip3 install pycodestyle
      script:
        - pycodestyle *.py assistance/*.py || true
    - stage: pylintcheck
      before_script:
        - pip3 install pylint
      script:
        - pylint --exit-zero *.py assistance/*.py
    - stage: test
      script:
        - python3 test_all.py
    - stage: test notebook
      before_script:
        - pip3 install scipy jupyter nbconvert ipykernel matplotlib
      script:
        - jupyter nbconvert to notebook --execute --ExecutePreprocessor.kernel_name=python3 --output output.ipynb service_test.ipynb
